flaskr/routes/access/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError
from flaskr.models import User
import re

class RegistrationForm(FlaskForm):
    email = StringField(label='Email',
                        id='field_email',
                        validators=[DataRequired(), Email()])
    password = PasswordField(label='Password',
                             id='field_password',
                             description='New password must contain a special character, an uppercase letter, a lowercase letter, a number and 8 charaters',
                             validators=[DataRequired()])
    confirm_password = PasswordField(label='Confirm Password', 
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField(label='Register',
                         id='button_register')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is taken. Please choose a different one.')
        
        
    def validate_password(self, password):
        if(len(password.data) < 8):
            raise ValidationError('Password must have at least 8 characters.')
        char_special = re.compile('[@_!#$%^&*()<>?/\|}{~:]')        
        if(char_special.search(password.data) == None):
            raise ValidationError('Password must contain a special character.')
        if(re.search(r'[A-Z]', password.data) == None):
            raise ValidationError('Password must contain at least 1 uppercase letter.')
        if(re.search(r'[a-z]', password.data) == None):
            raise ValidationError('Password must contain at least 1 lowercase letter.')
        if(re.search(r'\d', password.data) == None):
            raise ValidationError('Password must contain a number.')


class LoginForm(FlaskForm):
    email = StringField(label='Email',
                        id='field_email',
                        validators=[DataRequired(), Email()])
    password = PasswordField(label='Password', 
                             id='field_password',
                             validators=[DataRequired()])
    remember = BooleanField(label='Remember Me')
    submit = SubmitField(label='  Login  ',
                         id='button_login')
    

class RecoverPasswordForm(FlaskForm):
    email = StringField(label='Email',
                        id='field_email',
                        description="Forgot your account's password? Enter your email address and we'll send you a recovery link.",
                        validators=[DataRequired(), Email()])
    submit = SubmitField(label='Send recovery email',
                         id='button_send')

flaskr/routes/access/routes.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for, request
from flask_login import login_user, current_user, logout_user

from flaskr.models import User
from flaskr.routes.access.forms import LoginForm, RegistrationForm, RecoverPasswordForm
from flaskr import db, bcrypt

from flaskr.utility.file_system import FileSystem
from flaskr.utility.smtp_client import email_Sender

# Defining a blueprint
access_bp = Blueprint(
    'access_bp',
    __name__,
    template_folder='templates',
    static_folder='static',
    #static_url_path='/access'
)


# FILE SYSTEM MODULE FOR DATA
file_system = FileSystem()


@access_bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('access_bp.login'))


@access_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('interface_bp.dashboard'))
    """ Check the if user exist and then redirect them to the application page 
    """
    form = LoginForm()
    if form.validate_on_submit():
        user: User = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            if next_page == None:
                return redirect(url_for('interface_bp.dashboard'))
            else:
                return redirect(next_page)
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
            return redirect(url_for('access_bp.login'))
    return render_template('pages/login.html', title='Login', form=form)


@access_bp.route('/register', methods=['GET', 'POST'])
def register():    
    if current_user.is_authenticated:
        return redirect(url_for('interface_bp.dashboard'))
    """ Create a user account and then create his folder in 'dir_of_models'
    """
    form = RegistrationForm()
    if form.validate_on_submit():

        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()

        file_system.create_path_user(user.id)

        flash(f'Account created! Now you are able to log in', 'success')
        return redirect(url_for('access_bp.login'))
    return render_template('pages/register.html', title='Registrazione', form=form)

@access_bp.route('/recover_password', methods=['GET', 'POST'])
def recover_password(): 
    if current_user.is_authenticated:
        return redirect(url_for('interface_bp.dashboard'))
    """ Create a user account and then create his folder in 'dir_of_models'
    """
    form = RecoverPasswordForm()
    if form.validate_on_submit():
        user: User = User.query.filter_by(email=form.email.data).first()
        if user:
            """
            DA TROVARE UN MODO PER GENERARE UNA PASSWORD RANDOM
            AGGIORNARE IL DB CON LA NUOVA PASSWORD
            hashed_password = bcrypt generate_password_hash(RANDOM PASSWORD).decode('utf-8')
            
            DA IMPLEMENTARE cambio nel DB
            CONTROLLARE LE IMPOSTAZIONI DEL CLIENT PER L'INVIO

            subject = 'Recupero password Flask'
            body = "La tua nuova password per l'account flask è" + RANDOM PASSWORD
            isHtml = False

            client = email_Sender()
            client.create_message(form.email.data,subject,body,isHtml)
            client.send_email()

            """
        flash(f'Email sent! Check your mailbox.', 'success')
        return redirect(url_for('access_bp.login'))
    return render_template('pages/recover.html', title='Recupero', form=form)

flaskr/routes/access/templates/mainAccess.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('access_bp.static', filename='access/mainAccess.css') }}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='bootstrap/bootstrap-4.3.1.min.css') }}"
    />
    <!--
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    -->
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='bootstrap/jquery-3.3.1.slim.min.js')}}"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='bootstrap/bootstrap-4.3.1.bundle.min.js')}}"
    ></script>
    <!--
    <script
    src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    -->
    <title>{{ title }}</title>
  </head>

  <body>
    <img src="/static/A-Logo_Univr_Dip_Informatica_2016-02.png" alt="" width="" height="110">
    <div class="form-style">
        {% block content %}
        {% endblock %}
    </div>
  </body>
</html>

flaskr/routes/access/templates/pages/login.html
{% extends "mainAccess.html" %}
{% block content %}
    
    <form method="POST" action="">
        <div class="modal-dialog"> 
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Login</h4>
                </div>
                {{ form.hidden_tag() }}
                <div class="modal-body">
                    {{ form.email.label(class="form-control-label")}}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control") }}
                    {% endif %}

                    <br />

                    {{ form.password.label(class="form-control-label")}}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control") }}
                    {% endif %}

                    <br />

                    <div>
                        {% with messages = get_flashed_messages(with_categories=true) %}
                            {% if messages %}
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category }} alert-dismissible fade show">
                                    {{ message }}                                    
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endfor %}
                            {% endif %}
                        {% endwith %}
                    </div>
                </div>
                <div class="modal-footer form-footer">
                    <div class="text-muted">
                        <a class="btn btn-info" href="{{ url_for('access_bp.register') }}">Create an account</a>
                        <!--
                        <a class="btn btn-warning" href="{{ url_for('access_bp.recover_password') }}">Forgot password ?</a>
                        -->
                    </div>
                    <div>
                        {{ form.submit(class="btn btn-success") }}
                    </div>
                </div>
            </div>
        </div>        
    </form>

{% endblock %}

flaskr/routes/access/templates/pages/recover.html
{% extends "mainAccess.html" %}
{% block content %}
    
    <form method="POST" action="">
        <div class="modal-dialog"> 
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Recover password</h4>
                    <h1 class="modal-title">MANCA IL SERVER SMTP, NON INVIA LE EMAIL</h1>
                </div>
                {{ form.hidden_tag() }}
                <div class="modal-body">
                    
                    {{ form.email.label(class="form-control-label")}}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control") }}
                    {% endif %}
                    
                    <br />

                <div class="modal-footer form-footer">
                    <div class="text-muted">
                        <a class="btn btn-info" href="{{ url_for('access_bp.login') }}">Return to Login</a>
                    </div>
                    <div>
                        {{ form.submit(class="btn btn-success") }}
                    </div>
                </div>
            </div>
        </div>

        
    </form>

{% endblock %}

flaskr/routes/access/templates/pages/register.html
{% extends "mainAccess.html" %}
{% block content %}
    
    <form method="POST" action="">
        <div class="modal-dialog"> 
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Join Today</h4>
                </div>
                {{ form.hidden_tag() }}
                <div class="modal-body">
                    
                    {{ form.email.label(class="form-control-label")}}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control") }}
                    {% endif %}
                    
                    <br />

                    {{ form.password.label(class="form-control-label")}}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <label class="form-control-label" for="field_password">{{form.password.description}}</label>
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control") }}
                        <label class="form-control-label" for="field_password">{{form.password.description}}</label>
                    {% endif %}
                        
                    <br />

                    {{ form.confirm_password.label(class="form-control-label")}}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control") }}
                    {% endif %}
                    
                </div>
                <div class="modal-footer form-footer">
                    <div class="text-muted">
                        Already Have An Account? <a class="btn btn-info" href="{{ url_for('access_bp.login') }}">Login</a>
                    </div>
                    <div>
                        {{ form.submit(class="btn btn-success") }}
                    </div>
                </div>
            </div>
        </div>

        
    </form>

{% endblock %}