flaskr/routes/interface/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, IntegerField
from wtforms.validators import DataRequired, Email, Length, ValidationError, Optional, InputRequired
from flaskr.models import User
from flask_login import current_user
import re

class AccountForm(FlaskForm):
    email = StringField(label='Email',
                        id='field_email',
                        description='Type new email',
                        validators=[DataRequired(), Email()])
    password = PasswordField(label='Password',
                             id='field_password',
                             description='New password must contain a special character, an uppercase letter, an lowercase letter, a number and 8 charaters',
                             validators=[Optional()])
    update = SubmitField(label='Update',
                         id='button_update')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('That email is taken. Please choose a different one.')
        
    def validate_password(self, password):
        if password.data != "":
            if(len(password.data) < 8):
                raise ValidationError('Password must have at least 8 characters.')
            char_special = re.compile('[@_!#$%^&*()<>?/\|}{~:]')        
            if(char_special.search(password.data) == None):
                raise ValidationError('Password must contain a special character.')
            if(re.search(r'[A-Z]', password.data) == None):
                raise ValidationError('Password must contain at least 1 uppercase letter.')
            if(re.search(r'[a-z]', password.data) == None):
                raise ValidationError('Password must contain at least 1 lowercase letter.')
            if(re.search(r'\d', password.data) == None):
                raise ValidationError('Password must contain a number.')
        


class ModelForm(FlaskForm):
    model_dir = StringField(label='Model Output Directory:',
                            id="field_model_dir",
                            description='Type a new folder name or select an existing folder',
                            validators=[DataRequired(), Length(max=20)])
    file_input = FileField(label='Model input:',
                           id="field_file_input",
                           description='Choose a CSV input file',
                           validators=[FileRequired(), FileAllowed(['csv'], 'Only one CVS file')])
    files_output = FileField(label='Model expected outputs:',
                                     id="field_files_output",
                                     description='Choose multiple CSV for expected output',
                                     validators=[FileRequired(), FileAllowed(['csv'], 'Only CVS files')])
    window = IntegerField(label='Window:',
                          id="field_window",
                          description='Enter a integer value from 0',
                          validators=[Optional()])
    modelname = StringField(label='Model Result Name:',
                            id="field_model_name",
                            description='Before the name there is always current year_month_day_hour_min_sec',
                            validators=[InputRequired(), Length(max=20)])
    test = BooleanField(label='Test:',
                        id="field_test",
                        validators=[Optional()],
                        default=False)
    submit = SubmitField(label='Run Script',
                         id="submit_button")

    def validate_window(self, window):
        if window.data < 0:
            raise ValidationError('Must be greater or equal than 0')

flaskr/routes/interface/routes.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for, session, request
from flask_login import login_required, current_user

from flaskr.routes.interface.forms import AccountForm, ModelForm
from flaskr.utility.file_system import FileSystem
#from flaskr.utility.run_scripts import GenerateRegressionModel
from flaskr.models import User
from flaskr import db, bcrypt

# Defining a blueprint
interface_bp = Blueprint(
    'interface_bp',
    __name__,
    template_folder='templates',
    static_folder='static',
    #static_url_path='/interface'
)

# FILE SYSTEM MODULE FOR DATA
filesystem = FileSystem()


@interface_bp.route('/dashboard')
@login_required
def dashboard():
    return render_template('pages/dashboard.html')


@interface_bp.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = AccountForm()
    if request.method == 'GET':
        form.email.data = current_user.email
        #form.password.data = current_user.password
    elif request.method == 'POST':
        if form.validate_on_submit():
            current_user.email = form.email.data
            if form.password.data != "":
                current_user.password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            db.session.commit()
            flash('Data updated', category='success')
            return redirect(url_for('interface_bp.account'))

    return render_template('pages/account.html', form=form)


@interface_bp.route('/file_manager')
@login_required
def file_manager():
    return render_template('pages/file_manager.html')


@interface_bp.route('/regression_calculator', methods=['GET', 'POST'])
@login_required
def regression_calculator():
    form = ModelForm()
    vis_dir = filesystem.get_visible_directory(current_user.id)
    phase = 0
    window = ''
    test = False
    session['runned'] = False
    if request.method == 'POST':
        if form.validate_on_submit():
            # Get the name of the directory of the model
            session['model_dir'] = filesystem.get_secure_filename(request.form.get('model_dir'))            

            # Get the files
            file1 = request.files['file_input']
            files = request.files.getlist("files_output")

            # Checking extensions of files
            check_result = filesystem.check_files_extension(file1, files)
            if check_result != None:
                flash(check_result, 'danger')
                phase = 1 # show error on phase 1, do not start running
                return render_template('pages/regressionCalculator.html', model_dirs=vis_dir, form=form, phase=phase)

            # Iterate for each file in the files List, and Save them
            filesystem.save_a_uploaded_input(file1,current_user.id)

            filesystem.save_all_uploaded_output(files,current_user.id)

            session['filename'] = filesystem.get_time_secure_filename(request.form.get('modelname')) # type: ignore
            window = str(request.form.get('window'))
            test = bool(request.form.get('test'))
            phase = 2 # start running

            #return redirect(url_for('interface_bp.regression_calculator'))
        else:
            phase = 1 # show error on phase 1, do not start running
            return render_template('pages/regressionCalculator.html', model_dirs=vis_dir, form=form, phase=phase)

    return render_template('pages/regressionCalculator.html', model_dirs=vis_dir, form=form, phase=phase, data_window=window, data_test=test)


@interface_bp.route('/about')
@login_required
def about():
    return render_template('pages/about.html')

flaskr/routes/interface/templates/mainInterface.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='bootstrap/bootstrap-4.3.1.min.css') }}"
    />
    <!--  
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    -->
    <link
    rel="stylesheet"
    type="text/css"
    href="{{ url_for('interface_bp.static', filename='interface/css/mainInterface.css') }}"
    />  
    {% block css %}
    {% endblock css %}
    <script
    type="text/javascript"
    src="{{ url_for('interface_bp.static', filename='interface/javascript/mainInterface.js')}}"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='bootstrap/popper-1.16.1.min.js')}}"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='bootstrap/jquery-3.3.1.slim.min.js')}}"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='bootstrap/bootstrap-4.3.1.bundle.min.js')}}"
    ></script>
    <!--
    <script 
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" 
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" 
      crossorigin="anonymous">
    </script>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    -->
    {% block scripts %}
    {% endblock scripts %}
    <title>Models Calculator</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-light main-navbar">
        <a class="navbar-brand" hidden>Navbar</a>
        <img src="/static/A-Logo_Univr_Dip_Informatica_2016-02.png" alt="" width="" height="55">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
              <a id="button_dashboard" class="btn btn-primary" href="{{ url_for('interface_bp.dashboard') }}"> return to Dashboard</a>
            </li>
            <li class="nav-item" hidden>
              <a class="nav-link active" href="#">Features</a>
            </li>
            <!--
            <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            -->
          </ul>
          <a class="btn btn-success my-2 my-sm-0" href="{{ url_for('access_bp.logout') }}">
            Logout
          </a>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
  </body>
</html>

flaskr/routes/interface/templates/pages/about.html
{% extends "mainInterface.html" %} {% block css %}
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('interface_bp.static', filename='interface/css/about.css') }}"
/>
{% endblock css %} {% block scripts %}
<!--
<script 
    src="{{ url_for('interface_bp.static', filename='interface/javascript/about.js')}}" 
    type="text/javascript">
</script>-->
{% endblock scripts %} {% block content %}
<div class="container">
  <div class="row text-center my-4 mytitle">
    <h1>About</h1>
  </div>
  <div class="row text-center my-4 mytitle">
    <h2>This website is part of the project "Fiera dell'agicoltura".</h2>
    <h2>It was made in collaboration with:</h2>
    <h2>Catello Pane</h2>
    <h2>Claudio Tomazzoli</h2>
    <h2>Davide Quaglia</h2>
    <h2>Elia Brentarolli</h2>
    <h2>Gianni Donadon</h2>
    <h2>Mariano Ceccato</h2>
    <h2>Matteo Fiorini</h2>
    <h2>Paolo Guarino</h2>
    <h2>Sara Migliorini</h2>
    <h2>Tiziano Villa</h2>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-md-4">
      <img
        class="d-block w-100"
        src="/static/interface/image/Volantino-generale.jpg"
        alt="Generale"
      />
    </div>
    <div class="col-md-4">
      <img
        class="d-block w-100"
        src="/static/interface/image/Volantino-CREA.jpg"
        alt="Crea"
      />
    </div>
    <div class="col-md-4">
      <img
        class="d-block w-100"
        src="/static/interface/image/Volantino-data-science.jpg"
        alt="Data science"
      />
    </div>
  </div>
  {% endblock content %}
</div>

flaskr/routes/interface/templates/pages/account.html
{% extends "mainInterface.html" %}

{% block css %}
<link
rel="stylesheet"
type="text/css"
href="{{ url_for('interface_bp.static', filename='interface/css/account.css') }}"
/>  
{% endblock css %}

{% block scripts %}
<script 
    src="{{ url_for('interface_bp.static', filename='interface/javascript/account.js')}}" 
    type="text/javascript">
</script>
{% endblock scripts %}

{% block content %}
<div class="container">
    <div class="row text-center my-4 mytitle" >
        <h1>My account</h1>
    </div>
    <div class="row justify-content-md-center">
        <div class="col-md-6">
            <h3>You can edit only your email or password or both. Is show the current email, but not password for security reasons.</h3>
        </div>    
    </div>
    <div class="row justify-content-md-center">
        <div class="col-md-6">
            <div>
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} alert-dismissible fade show">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
            <div class="form-section">
                <form id="uploadForm" action="" method="post" enctype="multipart/form-data" autocomplete="off">
                    {{ form.hidden_tag() }}
                    
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label")}}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control") }}
                        {% endif %}
                    </div>
                    
                    <div class="form-group">
                        {{ form.password.label(class="form-control-label")}}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <label class="form-control-label" for="field_password">{{form.password.description}}</label>
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control") }}
                            <label class="form-control-label" for="field_password">{{form.password.description}}</label>
                        {% endif %}
                    </div>
                    <div>
                        {{ form.update(class="btn btn-success") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

flaskr/routes/interface/templates/pages/dashboard.html
{% extends "mainInterface.html" %}

{% block css %}
<link
rel="stylesheet"
type="text/css"
href="{{ url_for('interface_bp.static', filename='interface/css/dashboard.css') }}"
/>  
{% endblock css %}

{% block scripts %}
{% endblock scripts %}

{% block content %}

<div>
    <div class="container">      
        <div class="row text-center my-4" style="flex-direction: column !important;">
          <h1>Dashboard - Choose a function</h1>
      </div>
      <div id="first-row" class="row">
        <div class="col-md-4">
          <div class="card border-primary text-center">
            <div class="card-body">
                <a href="{{ url_for('interface_bp.account') }}">
                    <h4 class="card-title">My account</h4>
                </a>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card border-primary text-center">
            <div class="card-body" >
                <a href="{{ url_for('interface_bp.file_manager') }}">
                    <h4 class="card-title">File manager</h4>
                </a>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card border-primary text-center">
            <div class="card-body">
                <a href="{{ url_for('interface_bp.regression_calculator') }}">
                    <h4 class="card-title">Regression Model Calculator</h4>
                </a>
            </div>
          </div>
        </div>
      </div>
      <div id="second-row" class="row">
        <div class="col-md-4">
          <div class="card border-primary text-center">
            <div class="card-body">
                <a href="{{ url_for('interface_bp.about') }}">
                    <h4 class="card-title">About</h4>
                </a>
            </div>
          </div>
        </div>
        <div class="col-md-4" hidden>
          <div class="card border-primary text-center">
            <div class="card-body">
                <a href="{{ url_for('interface_bp.regression_calculator') }}">
                    <h4 class="card-title">Regression Model Calculator</h4>
                </a>
            </div>
          </div>
        </div>
        <div class="col-md-4" hidden>
          <div class="card border-primary text-center">
            <div class="card-body">
                <a href="{{ url_for('interface_bp.regression_calculator') }}">
                    <h4 class="card-title">Regression Model Calculator</h4>
                </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

flaskr/routes/interface/templates/pages/regressionCalculator.html
{% extends "mainInterface.html" %}

{% block css %}
<link
rel="stylesheet"
type="text/css"
href="{{ url_for('interface_bp.static', filename='interface/css/regressionCalculator.css') }}"
/>  
{% endblock css %}

{% block scripts %}
<script 
    src="{{ url_for('interface_bp.static', filename='interface/javascript/regressionCalculator.js')}}" 
    type="text/javascript">
</script>
{% endblock scripts %}

{% block content %}
<div class="container">
    <div class="row text-center my-4 mytitle" >
        <h1>Regression Model Calculator</h1>
    </div>
    <div class="row">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible fade in show">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>    
    <div class="row">
        <div class="col-md-6 border border-secondary rounded">
            <h1>Calculation settings</h1>
            <div class="form-section">
                <form id="uploadForm" action="" method="post" enctype="multipart/form-data" autocomplete="off">
                    {{ form.hidden_tag() }}
                    
                    <div class="form-group">
                        {{ form.model_dir.label(class="form-control-label text-bold")}}
                        <div class="input-group">
                            {{ form.model_dir(class="form-control", placeholder="Type a new folder name or select an existing folder") }}
                            <div class="input-group-append">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Select</button>

                                <ul class="dropdown-menu">
                                    {% for dir in model_dirs %}
                                        <li><a class="dropdown-item" onclick="selectModelDir('{{ dir }}')">{{ dir }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form.modelname.label(class="form-control-label text-bold")}}
                        <label class="form-control-label text-a-bit-bold" for="modelname">{{form.modelname.description}}</label>
                        {{ form.modelname(placeholder="Type the name of result file", class="form-control") }}
                    </div>
                    <div class="form-group">
                        <div class="form-control-label text-a-bit-bold">Supported input date:</div>
                        <div class="form-control-label text-a-bit-bold">- 18/12/2000 10:15:00</div>
                        <div class="form-control-label text-a-bit-bold">- 2000-12-20 10:15:00</div>
                        <div class="form-control-label text-a-bit-bold">- 2000_12_20_10_1 </div>
                    </div>
                    <div class="form-group">
                        {{ form.file_input.label(class="form-control-label text-bold")}}                     
                        <div class="custom-file">
                            {% if form.file_input.errors %}
                                {{ form.file_input(class="custom-file-input form-control is-invalid", onchange="updateFileInput()") }}
                                <label class="custom-file-label" for="file_input">{{form.file_input.description}}</label>
                                <div class="invalid-feedback">
                                    {% for error in form.file_input.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                    </div>
                            {% else %}
                                {{ form.file_input(class="custom-file-input form-control", onchange="updateFileInput()") }}
                                <label class="custom-file-label" for="file_input">{{form.file_input.description}}</label>
                            {% endif %}
                        </div>
                    </div>
                    
                    <div class="form-group">
                        {{ form.files_output.label(class="form-control-label text-bold")}}
                        <div id="container_field_files_output" class="custom-file">
                            {% if form.files_output.errors %}
                                {{ form.files_output(multiple="", class="custom-file-input form-control is-invalid", onchange="updateFilesOutput()") }}
                                <label id="label_field_files_output" class="custom-file-label fit-content" for="files_output">{{form.files_output.description}}</label>
                                <div class="invalid-feedback">
                                    {% for error in form.files_output.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                    </div>
                            {% else %}
                                {{ form.files_output(multiple="", class="custom-file-input form-control", onchange="updateFilesOutput()") }}
                                <label id="label_field_files_output" class="custom-file-label fit-content" for="files_output">{{form.files_output.description}}</label>
                            {% endif %}
                        </div>
                    </div>
                    
                    <div class="form-group">
                        {{ form.window.label(class="form-control-label text-bold")}}
                        <div class="input-group">
                            {% if form.window.errors %}
                                {{ form.window(placeholder="Enter a integer value from 0", class="form-control is-invalid") }}
                                <div class="input-group-append">
                                    
                                </div>
                                <div class="invalid-feedback">
                                    {% for error in form.window.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                    </div>
                            {% else %}
                                {{ form.window(placeholder="Enter a integer value from 0", class="form-control") }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form.test.label(class="form-control-label text-bold")}}
                        {{ form.test() }}
                    </div>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-primary", onclick="showUploading()") }}
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-6 border border-secondary rounded">
            <h1>Phases</h1>
            <!--                
            <button type="button" name="age" id="age" data-toggle="modal" data-target="#add_data_Modal" class="btn btn-secondary">Broker Config</button>
            <div id="add_data_Modal" class="modal fade">
                <div class="modal-dialog">  
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Broker Config</h4>
                        </div>
                        <div class="modal-body" align="left">
                            <label>Host Name</label>
                            <input type="text" name="host_name" id="host_name" class="form-control" />
                            <br />
                            <label>Host Password</label>
                            <input type="password" name="password" id="password" class="form-control" />
                            <br />
                            <label>Broker IP</label>
                            <input type="text" name="IP" id="IP" class="form-control" />
                            <br />  
                            <label>Nome topic</label>
                            <input type="text" name="topic" id="topic" class="form-control" />
                            <br />  
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
            -->
            <div id="before_result_uploading" style="display: flex;">
                <h3 style="padding-right: 5px;">Phase 1 - Checking settings.</h3>
                <h3 id="before_result_uploading_error" style="color: red;display: none;">Error</h3>
                <h3 id="before_result_uploading_ok" style="color: green;display: none;">OK</h3>
            </div>
            <div style="display: none;">
                <div id="process_phase">{{phase}}</div>
                <div id="process_data_window">{{data_window}}</div>
                <div id="process_data_test">{{data_test}}</div>
            </div>
            <div id="before_result_processing" style="border-top-style: solid;border-width: 1px;">
                <h3 style="padding-right: 5px;">Phase 2 - Start processing. This may take some minutes.</h3>
                <div style="display: flex;">
                    <h3>Processing time:</h3>
                    <div class="timer h3">
                        <span class="hour">00</span>h <span class="minute">00</span>m <span class="second">00</span>s
                    </div>
                </div>
                <div id="before_result_processing_bar" class="progress" style="position: relative;">
                    <div class="progress-bar progress-bar-striped indeterminate">
                </div>                
            </div>
            <div id="result_body" style="border-top-style: solid;border-width: 1px;">
                <h3 style="padding-right: 5px;">Phase 3 - Result.</h3>         
                <div id="result_body_output_body">
                    <textarea name="result" id="result_body_output" cols="34" rows="8" style="resize: both;"></textarea>
                </div>
                <h4 id="result_body_message"></h4>  
                <br>   
                <div id="result_body_buttons">
                    <a class="btn btn-info" href="{{ url_for('interface_bp.file_manager') }}">Go to file manager to download or delete</a>
                    <!--
                    <button type="button" id="actionButton" onclick="handleAction('save', event)" class="btn btn-success">Save</button>
                    <button type="button" id="actionButton" onclick="handleAction('delete', event)" class="btn btn-danger">Delete</button>
                    -->
                </div>
            </div>
        </div>
    </div>
{% endblock %}